/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import {MeshTransmissionMaterial, useGLTF} from '@react-three/drei'
import {BackSide} from 'three';
import {Sofa} from './Sofa.jsx';

export function Room(props) {
  const {nodes, materials} = useGLTF('/RoomDubai.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground.geometry}
        material={nodes.Ground.material}
        position={[-2.584, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorLamp.geometry}
        material={materials['Material.008']}
        position={[6.32, 2.223, 5.553]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ceiling.geometry}
        position={[-2.584, 4.942, 0]}
      >
        <meshStandardMaterial color="#ffffff" side={BackSide}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GlassWindow.geometry}
        position={[-5.604, 3.35, -4.5]}
        rotation={[0, 0, -Math.PI / 2]}
      >
        <MeshTransmissionMaterial
          clearcoat={1}
          clearcoatRoughness={0}
          transmission={1}
          chromaticAberration={0.03}
          anisotrophicBlur={0.1}
          roughness={0}
          thickness={0.2}
          ior={1.1}
          distortion={0.1}
          distortionScale={0.2}
          temporalDistortion={0.2}
        />

      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BigGlassWindow.geometry}
        material={materials['Material.001']}
        position={[1., 4.75, 22.022]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <MeshTransmissionMaterial
          clearcoat={1}
          clearcoatRoughness={0}
          transmission={1}
          chromaticAberration={0.03}
          anisotrophicBlur={0.1}
          roughness={0}
          thickness={0.2}
          ior={1.1}
          distortion={0.1}
          distortionScale={0.2}
          temporalDistortion={0.2}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TableLamp.geometry}
        material={materials._1___Default}
        position={[-1.607, 5.84, -4.68]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[3.644, 4.268, 2.245]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials.Metal_Escuro}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42_1.geometry}
          material={materials.Metal_Branco}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42_2.geometry}
          material={materials.Plastico}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42_3.geometry}
          material={materials.Material_214597}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42_4.geometry}
          material={materials.cromado}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42_5.geometry}
          material={materials.Fio2}
        />
      </group>
      <group position={[-2.052, 4.268, 2.245]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42001.geometry}
          material={materials.Metal_Escuro}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42001_1.geometry}
          material={materials.Metal_Branco}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42001_2.geometry}
          material={materials.Plastico}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42001_3.geometry}
          material={materials.Material_214597}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42001_4.geometry}
          material={materials.cromado}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42001_5.geometry}
          material={materials.Fio2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rod.geometry}
        material={materials.lambert1}
        position={[-5.397, 4.189, -5.601]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WindowFrame.geometry}
        material={materials.lambert1}
        position={[-5.536, 2.985, -4.646]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials.zhuoyi}
        position={[-2.351, 1.093, -5.836]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair001.geometry}
        material={materials.zhuoyi}
        position={[-2.287, 1.093, -3.085]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair002.geometry}
        material={materials.zhuoyi}
        position={[-1.145, 1.093, -3.085]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair003.geometry}
        material={materials.zhuoyi}
        position={[-1.071, 1.093, -5.836]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Candle.geometry}
        material={materials.niunai}
        position={[-1.692, 1.452, -4.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Candle002.geometry}
        material={materials.niunai}
        position={[-1.692, 1.452, -4.604]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass001.geometry}
        material={materials.boli}
        position={[-1.694, 1.452, -4.606]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass.geometry}
        material={materials.boli}
        position={[-1.694, 1.452, -4.606]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dishes.geometry}
        material={materials.qita}
        position={[-1.694, 1.452, -4.606]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leafs.geometry}
        material={materials.lvzhi}
        position={[-1.694, 1.452, -4.606]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table.geometry}
        material={materials.zhuoyi}
        position={[-1.694, 1.452, -4.606]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TableCloth001.geometry}
        material={materials.bu}
        position={[-1.694, 1.452, -4.606]}
      />
      <Sofa/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Carpet.geometry}
        material={materials.Mat_1}
        position={[3.558, 0.033, 2.398]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[-5.449, 2.815, 2.487]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials.RedLight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials.Screen1}
        />
      </group>
      <group position={[-5.075, 0.499, 2.445]} rotation={[0, 1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007.geometry}
          material={materials.tvstandmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_1.geometry}
          material={materials.tvstand}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall.geometry}
        material={nodes.Wall.material}
        position={[7.791, 2.47, -0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall001.geometry}
        material={nodes.Wall001.material}
        position={[-5.908, 2.47, -0.229]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall002.geometry}
        material={nodes.Wall002.material}
        position={[0, 0.886, -8.44]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall003.geometry}
        material={nodes.Wall003.material}
        position={[7.075, 2.47, 7.828]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall004.geometry}
        material={nodes.Wall004.material}
        position={[0.961, 2.47, 22.047]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_2.geometry}
        material={materials.Curtain}
        position={[-5.506, 3.119, -3.279]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_1.geometry}
        material={materials.Curtain}
        position={[-5.413, 2.426, -5.125]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stair.geometry}
        material={nodes.Stair.material}
        position={[0, 0.175, -6.486]}
      />
    </group>
  )
}

useGLTF.preload('/RoomDubai.glb')
